export interface Document {
  id: string;
  title: string;
  description: string;
  filiere: string;
  niveau: string;
  annee: string;
  type: string;
  format: string;
  size: string;
  downloadable: boolean;
  dateAdded: string;
  author: string;
  tags: string[];
}

export const FILIERES = [
  "Informatique",
  "Gestion",
  "Droit",
  "Économie",
  "Marketing",
  "Comptabilité",
  "Ressources Humaines",
];

export const NIVEAUX = ["Licence 1", "Licence 2", "Licence 3", "Master 1", "Master 2"];
export const ANNEES = ["2025-2026", "2024-2025", "2023-2024", "2022-2023"];
export const TYPES = [
  "Cours",
  "TD",
  "TP",
  "Examen",
  "Corrigé",
  "Mémoire",
  "Rapport de stage",
  "Fiche de révision",
];

export const documents: Document[] = [
  {
    id: "1",
    title: "Introduction à l'algorithmique",
    description: "Cours complet sur les bases de l'algorithmique : structures de contrôle, boucles, tableaux.",
    filiere: "Informatique",
    niveau: "Licence 1",
    annee: "2025-2026",
    type: "Cours",
    format: "PDF",
    size: "2.4 MB",
    downloadable: true,
    dateAdded: "2026-01-15",
    author: "Prof. Diallo",
    tags: ["algorithmique", "programmation", "bases"],
  },
  {
    id: "2",
    title: "Examen final — Droit des affaires",
    description: "Sujet d'examen du premier semestre avec barème détaillé.",
    filiere: "Droit",
    niveau: "Licence 2",
    annee: "2024-2025",
    type: "Examen",
    format: "PDF",
    size: "890 KB",
    downloadable: false,
    dateAdded: "2025-12-20",
    author: "Prof. Mbaye",
    tags: ["droit", "affaires", "examen"],
  },
  {
    id: "3",
    title: "TD — Statistiques descriptives",
    description: "Exercices pratiques avec corrections sur les statistiques descriptives.",
    filiere: "Économie",
    niveau: "Licence 1",
    annee: "2025-2026",
    type: "TD",
    format: "PDF",
    size: "1.7 MB",
    downloadable: true,
    dateAdded: "2026-01-28",
    author: "Dr. Ndiaye",
    tags: ["statistiques", "mathématiques", "td"],
  },
  {
    id: "4",
    title: "Mémoire — Transformation digitale des PME",
    description: "Étude complète sur l'impact de la digitalisation dans les petites et moyennes entreprises.",
    filiere: "Gestion",
    niveau: "Master 2",
    annee: "2024-2025",
    type: "Mémoire",
    format: "PDF",
    size: "5.2 MB",
    downloadable: true,
    dateAdded: "2025-09-10",
    author: "Aminata Fall",
    tags: ["digital", "PME", "transformation", "mémoire"],
  },
  {
    id: "5",
    title: "TP — Bases de données relationnelles",
    description: "Travaux pratiques SQL : création, interrogation et optimisation de bases de données.",
    filiere: "Informatique",
    niveau: "Licence 2",
    annee: "2025-2026",
    type: "TP",
    format: "PDF",
    size: "3.1 MB",
    downloadable: true,
    dateAdded: "2026-02-01",
    author: "Prof. Sy",
    tags: ["SQL", "bases de données", "tp"],
  },
  {
    id: "6",
    title: "Corrigé — Marketing stratégique",
    description: "Correction détaillée de l'examen de marketing stratégique avec explications.",
    filiere: "Marketing",
    niveau: "Licence 3",
    annee: "2024-2025",
    type: "Corrigé",
    format: "PDF",
    size: "1.2 MB",
    downloadable: true,
    dateAdded: "2025-11-15",
    author: "Dr. Cissé",
    tags: ["marketing", "stratégie", "corrigé"],
  },
  {
    id: "7",
    title: "Fiche de révision — Comptabilité générale",
    description: "Synthèse des concepts clés de la comptabilité : bilan, compte de résultat, amortissements.",
    filiere: "Comptabilité",
    niveau: "Licence 1",
    annee: "2025-2026",
    type: "Fiche de révision",
    format: "PDF",
    size: "650 KB",
    downloadable: true,
    dateAdded: "2026-01-20",
    author: "Prof. Ba",
    tags: ["comptabilité", "révision", "bilan"],
  },
  {
    id: "8",
    title: "Rapport de stage — Cabinet RH",
    description: "Rapport de stage de 3 mois dans un cabinet de ressources humaines à Dakar.",
    filiere: "Ressources Humaines",
    niveau: "Master 1",
    annee: "2024-2025",
    type: "Rapport de stage",
    format: "PDF",
    size: "4.8 MB",
    downloadable: false,
    dateAdded: "2025-10-05",
    author: "Ousmane Sow",
    tags: ["RH", "stage", "rapport"],
  },
  {
    id: "9",
    title: "Cours — Programmation web",
    description: "HTML, CSS, JavaScript et React : les fondamentaux du développement web moderne.",
    filiere: "Informatique",
    niveau: "Licence 2",
    annee: "2025-2026",
    type: "Cours",
    format: "PDF",
    size: "6.3 MB",
    downloadable: true,
    dateAdded: "2026-02-03",
    author: "Dr. Traoré",
    tags: ["web", "HTML", "CSS", "JavaScript", "React"],
  },
  {
    id: "10",
    title: "Examen — Microéconomie",
    description: "Sujet et corrigé de l'examen de microéconomie du second semestre.",
    filiere: "Économie",
    niveau: "Licence 2",
    annee: "2023-2024",
    type: "Examen",
    format: "PDF",
    size: "1.1 MB",
    downloadable: true,
    dateAdded: "2024-06-15",
    author: "Prof. Diouf",
    tags: ["microéconomie", "examen", "corrigé"],
  },
  {
    id: "11",
    title: "TD — Droit constitutionnel",
    description: "Cas pratiques et dissertations sur les grands principes du droit constitutionnel.",
    filiere: "Droit",
    niveau: "Licence 1",
    annee: "2025-2026",
    type: "TD",
    format: "PDF",
    size: "2.0 MB",
    downloadable: true,
    dateAdded: "2026-01-10",
    author: "Prof. Guèye",
    tags: ["droit", "constitution", "td"],
  },
  {
    id: "12",
    title: "Cours — Gestion de projet",
    description: "Méthodologies Agile, Scrum et gestion de projet classique pour les managers.",
    filiere: "Gestion",
    niveau: "Master 1",
    annee: "2025-2026",
    type: "Cours",
    format: "PDF",
    size: "3.5 MB",
    downloadable: true,
    dateAdded: "2026-01-25",
    author: "Dr. Diop",
    tags: ["gestion", "projet", "agile", "scrum"],
  },
];